// export const GET_RATE_QUERY_KEY = 'GET_RATE_QUERY_KEY';
// export const GET_SOLD_QUERY_KEY = 'GET_SOLD_QUERY_KEY';
// export const GET_CREATED_AT_QUERY_KEY = 'GET_CREATED_AT_QUERY_KEY';
// export const GET_PRICE_QUERY_KEY = 'GET_PRICE_QUERY_KEY';
export const GET_HOME_QUERY_KEY = 'GET_HOME_QUERY_KEY';
