export const SEARCH_ORDER_QUERY_KEY = 'SEARCH_ORDER_QUERY_KEY';
export const GET_ORDER_BY_STATUS_QUERY_KEY = 'GET_ORDER_BY_STATUS_QUERY_KEY';
export const GET_ORDER_BY_TO_SHIP_QUERY_KEY = 'GET_ORDER_BY_TO_SHIP_QUERY_KEY';