export const GET_PRODUCT_QUERY_KEY = 'GET_PRODUCT_QUERY_KEY';
export const GET_FEATURED_PRODUCT_QUERY_KEY = 'GET_FEATURED_PRODUCT_QUERY_KEY';
export const SEARCH_PRODUCT_BY_NAME_QUERY_KEY = 'SEARCH_PRODUCT_BY_NAME_QUERY_KEY';
