export const GET_MY_TICKET_QUERY_KEY = 'GET_MY_TICKET_QUERY_KEY';
export const GET_TICKET_BY_ID_QUERY_KEY = 'GET_TICKET_BY_ID_QUERY_KEY';
export const GET_STAFF_TICKET_BY_STATUS_QUERY_KEY = 'GET_STAFF_TICKET_BY_STATUS_QUERY_KEY';
